name: Node.js Test

on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"

jobs:
  test:
    name: Node.js test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: >-
      ${{ !contains(github.event.head_commit.message, 'chore: ') }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest

    steps:
      - name: Handle line endings
        shell: bash
        if: runner.os == 'Windows'
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - uses: actions/checkout@v3

      # Source map format
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      # We explicitly do this to cache properly.
      - name: Install Rust
        uses: actions-rs/toolchain@v1

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: "cargo-debug-test"
          cache-on-failure: true

      - name: Install node dependencies
        shell: bash
        run: |
          yarn

      - name: Configure path (windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo $(yarn global bin) >> $GITHUB_PATH

      - name: Run tests (using turbo)
        run: |
          npx turbo run test
